// resources/js/admin/core/components/DeleteAction.vue
<template>
    <button type="button" class="btn btn-link text-danger text-decoration-none" @click="onOpen">delete</button>
    <ConfirmationDialog v-if="open" message="Delete the element?" :on-ok="onOk" :on-cancel="onCancel" />
</template>

<script setup>
import ConfirmationDialog from './ConfirmationDialog.vue';
import { ref } from 'vue';

const props = defineProps({
    onDelete: Function,
});

const open = ref(false);

function onOpen() {
    open.value = true;
}

function onOk() {
    props.onDelete();
    open.value = false;
}
function onCancel() {
    open.value = false;
}
</script>

// resources/js/admin/core/components/DeleteAction.jsx
import React, { useState } from 'react';
import ConfirmationDialog from './ConfirmationDialog';

export default function DeleteAction({ handleDelete }) {
    const [open, setOpen] = useState(false);

    const handleOk = () => {
        handleDelete();
        setOpen(false);
    }

    const handleCancel = () => {
        setOpen(false);
    }

    const handleClick = () => {
        setOpen(true);
    }

    return (
        <>
            <button type="button" className="btn btn-link text-danger text-decoration-none" onClick={handleClick}>delete</button>
            {open ? <ConfirmationDialog message="Delete the element?" handleOk={handleOk} handleCancel={handleCancel} /> : null}
        </>
    );
}
