// resources/js/admin/core/components/Notification.vue
<template>
    <div class="alert alert-dismissible fade show" :class="`alert-${notification.type}`">
        {{notification.message}}
        <button type="button" class="btn-close" aria-label="Close" @click="() => onClose(index)"></button>
    </div>
</template>

<script setup>
import { onMounted } from 'vue';

const props = defineProps({
    notification: Object,
    index: Number,
    onClose: Function,
});

onMounted(() => {
    setTimeout(() => {
        props.onClose(props.index);
    }, 5000);
});
</script>

// resources/js/admin/core/components/Notification.jsx
import React, { useEffect } from 'react';

export default function Notification({ notification, index, handleClose }) {
    useEffect(() => {
        setTimeout(() => {
            handleClose(index);
        }, 5000)
    }, [])

    return (
        <div className={`alert alert-${notification.type} alert-dismissible fade show`}>
            {notification.message}
            <button type="button" className="btn-close" aria-label="Close" onClick={() => handleClose(index)}></button>
        </div>
    );
}
