// resources/js/admin/core/components/NotificationCenter.vue
<template>
    <div class="notification-center">
        <Notification v-for="(notification, index) in notifications" :index="index" :notification="notification" :on-close="handleClose" />
    </div>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import Notification from './Notification.vue';

const notifications = ref([]);

function addNotification(event) {
    notifications.value.push(event.detail);
}

function handleClose(index) {
    const result = [...notifications.value];
    result.splice(index, 1);
    notifications.value = result;
}

onMounted(() => {
    window.addEventListener('submit-notification', addNotification);

    return () => {
        window.removeEventListener('submit-notification', addNotification);
    };
})
</script>

<style lang="scss">
.notification-center {
    position: fixed;
    right: 0;
    z-index: 1000;
    width: 24em;
    padding: 1rem;
}
</style>

// resources/js/admin/core/components/NotificationCenter.jsx
import React, { useEffect, useState } from 'react';
import Notification from './Notification';

export default function NotificationCenter() {
    const [notifications, setNotifications] = useState([]);

    const handleNotification = (event) => {
        setNotifications(state => {
            return [...state, event.detail];
        });
    };

    useEffect(() => {
        window.addEventListener('submit-notification', handleNotification);

        return () => {
            window.removeEventListener('submit-notification', handleNotification);
        };
    }, []);

    const handleClose = (index) => {
        setNotifications(state => {
            const result = [...state];
            result.splice(index, 1);
            return result;
        });
    }

    return (
        <div className="notification-center">
            {notifications.map((notification, index) => {
                return (
                    <Notification index={index} notification={notification} handleClose={handleClose} />
                );
            })}
        </div>
    );
}
