// resources/js/admin/users/components/UserUpdatePasswordForm.vue
<template>
    <div class="container">
        <form action="#" @submit.prevent="onSubmit">
            <div class="mb-4">
                <label for="password" class="form-label">Password</label>
                <input type="password" id="password" class="form-control" :class="{'is-invalid': errors.password}" v-model="form.password" />
                <div v-if="errors.password" class="invalid-feedback">{{ errors.password[0] }}</div>
            </div>
            <div class="mb-4">
                <label for="password_confirmation" class="form-label">Password Confirmation</label>
                <input type="password" id="password_confirmation" class="form-control" :class="{'is-invalid': errors.password_confirmation}" v-model="form.password_confirmation" />
                <div v-if="errors.password_confirmation" class="invalid-feedback">{{ errors.password_confirmation[0] }}</div>
            </div>
            <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary px-4">Save</button>
            </div>
        </form>
    </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
import axios from 'axios';
import { useRouter } from 'vue-router';

const router = useRouter();

const props = defineProps({
    user: Object,
});

const errors = ref({});
const form = reactive({
    password: '',
    password_confirmation: '',
});

function onSubmit() {
    axios.patch(`/users/${props.user.id}`, form)
        .then(() => {
            window.dispatchEvent(new CustomEvent('submit-notification', {
                detail: { type: 'success', message: "User's password updated." }
            }));
            router.push('/users');
        })
        .catch(err => {
            if (err.response.status === 422) {
                errors.value = err.response.data.errors;
            }
        });
}
</script>

// resources/js/admin/users/components/UserUpdatePasswordForm.jsx
import { useNavigate } from 'react-router-dom';
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import axios from 'axios';
import classNames from 'classnames';

export default function UserUpdatePasswordForm({ user }) {
    const navigate = useNavigate();
    const [errors, setErrors] = useState({});
    const { handleSubmit, register } = useForm({
        mode: 'onBlur',
        reValidateMode: 'onBlur',
        defaultValues: {
            password: '',
            password_confirmation: '',
        },
    });

    const onSubmit = handleSubmit(data => {
        axios.patch(`/users/${user.id}`, data)
            .then(() => {
                window.dispatchEvent(new CustomEvent('submit-notification', {
                    detail: { type: 'success', message: "User's password updated." }
                }));
                navigate('/users');
            })
            .catch(err => {
                if (err.response.status === 422) {
                    setErrors(err.response.data.errors);
                }
            });
    });

    return (
        <div className="container">
            <form action="#" onSubmit={onSubmit}>
                <div className="mb-4">
                    <label htmlFor="password" className="form-label">Password</label>
                    <input type="password" id="password" className={classNames('form-control', { 'is-invalid': errors.password })} {...register('password')} />
                    { errors.password ? <div className="invalid-feedback">{errors.password[0]}</div> : null }
                </div>
                <div className="mb-4">
                    <label htmlFor="password_confirmation" className="form-label">Password Confirmation</label>
                    <input type="password" id="password_confirmation" className={classNames('form-control', { 'is-invalid': errors.password_confirmation })} {...register('password_confirmation')} />
                    { errors.password_confirmation ? <div className="invalid-feedback">{errors.password_confirmation[0]}</div> : null }
                </div>
                <div className="d-flex justify-content-end">
                    <button type="submit" className="btn btn-primary px-4">Save</button>
                </div>
            </form>
        </div>
    )
}
