// resources/js/admin/users/components/UserUpdateForm.jsx
import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import axios from 'axios';
import classNames from 'classnames';

export default function UserUpdateForm({ user }) {
    const navigate = useNavigate();
    const [errors, setErrors] = useState({});
    const { handleSubmit, register } = useForm({
        mode: 'onBlur',
        reValidateMode: 'onBlur',
        defaultValues: {
            name: user.name,
            email: user.email,
            role: user.role,
            enabled: user.enabled,
        },
    });

    const onSubmit = handleSubmit(data => {
        axios.put(`/users/${user.id}`, data)
            .then(() => {
                window.dispatchEvent(new CustomEvent('submit-notification', {
                    detail: { type: 'success', message: 'User updated.' }
                }));
                navigate('/users');
            })
            .catch(err => {
                if (err.response.status === 422) {
                    setErrors(err.response.data.errors);
                }
            });
    });

    return (
        <div className="container">
            <form action="#" onSubmit={onSubmit}>
                <div className="mb-4">
                    <label htmlFor="name" className="form-label">Name</label>
                    <input type="text" id="name" className={classNames('form-control', { 'is-invalid': errors.name })} {...register('name')} />
                    { errors.name ? <div className="invalid-feedback">{errors.name[0]}</div> : null }
                </div>
                <div className="mb-4">
                    <label htmlFor="email" className="form-label">Email</label>
                    <input type="email" id="email" className={classNames('form-control', { 'is-invalid': errors.email })} {...register('email')} />
                    { errors.email ? <div className="invalid-feedback">{errors.email[0]}</div> : null }
                </div>
                <div className="mb-4">
                    <label htmlFor="role" className="form-label">Role</label>
                    <select id="role" className={classNames('form-select', { 'is-invalid': errors.role })} {...register('role')}>
                        <option value="admin">Admin</option>
                        <option value="client">Client</option>
                    </select>
                    { errors.role ? <div className="invalid-feedback">{errors.role[0]}</div> : null }
                </div>
                <div className="mb-4 form-check">
                    <input type="checkbox" id="enabled" className={classNames('form-check-input', { 'is-invalid': errors.enabled })} {...register('enabled')} />
                    <label htmlFor="enabled" className="form-check-label">Enabled</label>
                    { errors.enabled ? <div className="invalid-feedback">{errors.enabled[0]}</div> : null }
                </div>
                <div className="d-flex justify-content-end">
                    <Link to="/users" className="btn btn-link">Back to users</Link>
                    <button type="submit" className="btn btn-primary px-4">Save</button>
                </div>
            </form>
        </div>
    );
}

// resources/js/admin/users/components/UserUpdateForm.vue
<template>
    <div class="container">
        <form action="#" @submit.prevent="onSubmit">
            <div class="mb-4">
                <label for="name" class="form-label">Name</label>
                <input type="text" id="name" class="form-control" :class="{'is-invalid': errors.name }" v-model="form.name" />
                <div v-if="errors.name" class="invalid-feedback">{{ errors.name[0] }}</div>
            </div>
            <div class="mb-4">
                <label for="email" class="form-label">Email</label>
                <input type="email" id="email" class="form-control" :class="{'is-invalid': errors.email }" v-model="form.email" />
                <div v-if="errors.email" class="invalid-feedback">{{ errors.email[0] }}</div>
            </div>
            <div class="mb-4">
                <label for="role" class="form-label">Role</label>
                <select id="role" class="form-select" :class="{'is-invalid': errors.role }" v-model="form.role">
                <option value="admin">Admin</option>
                <option value="client">Client</option>
                </select>
                <div v-if="errors.role" class="invalid-feedback">{{ errors.role[0] }}</div>
            </div>
            <div class="mb-4 form-check">
                <input type="checkbox" id="enabled" class="form-check-input" :class="{'is-invalid': errors.enabled }" v-model="form.enabled" />
                <label for="enabled" class="form-check-label">Enabled</label>
                <div v-if="errors.enabled" class="invalid-feedback">{{ errors.enabled[0] }}</div>
            </div>
            <div class="d-flex justify-content-end">
                <router-link to="/users" class="btn btn-link">Back to users</router-link>
                <button type="submit" class="btn btn-primary px-4">Save</button>
            </div>
        </form>
    </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
import axios from 'axios';
import { useRouter } from 'vue-router';

const router = useRouter();

const props = defineProps({
    user: Object,
});

const errors = ref({});
const form = reactive({
    name: props.user.name,
    email: props.user.email,
    role: props.user.role,
    enabled: !!props.user.enabled,
});

function onSubmit() {
    axios.put(`/users/${props.user.id}`, form)
        .then(() => {
            window.dispatchEvent(new CustomEvent('submit-notification', {
                detail: { type: 'success', message: 'User updated.' }
            }));
            router.push('/users');
        })
        .catch(err => {
            if (err.response.status === 422) {
                errors.value = err.response.data.errors;
            }
        });
}
</script>
