// resources/js/admin/users/UserCreate.jsx
import React, { useState } from 'react';
import { useForm } from 'react-hook-form';
import axios from 'axios';
import { Link, useNavigate } from 'react-router-dom';
import classNames from 'classnames';

export default function UserCreate() {
    const navigate = useNavigate();
    const [errors, setErrors] = useState({});
    const { handleSubmit, register } = useForm({
        mode: 'onBlur',
        reValidateMode: 'onBlur',
        defaultValues: {
            name: '',
            email: '',
            password: '',
            password_confirmation: '',
            role: 'client',
            enabled: true,
        },
    });

    const onSubmit = handleSubmit(data => {
        axios.post('/users', data)
            .then(() => {
                window.dispatchEvent(new CustomEvent('submit-notification', {
                    detail: { type: 'success', message: 'User created.' }
                }));
                navigate('/users');
            })
            .catch(err => {
                if (err.response.status === 422) {
                    setErrors(err.response.data.errors);
                }
            });
    });

    return (
        <div className="container">
            <div className="card border-0 shadow mt-4 mw-50e mx-auto">
                <div className="card-body">
                    <form action="#" onSubmit={onSubmit}>
                        <div className="mb-4">
                            <label htmlFor="name" className="form-label">Name</label>
                            <input type="text" id="name" className={classNames('form-control', { 'is-invalid': errors.name })} {...register('name')} />
                            { errors.name ? <div className="invalid-feedback">{errors.name[0]}</div> : null }
                        </div>
                        <div className="mb-4">
                            <label htmlFor="email" className="form-label">Email</label>
                            <input type="email" id="email" className={classNames('form-control', { 'is-invalid': errors.email })} {...register('email')} />
                            { errors.email ? <div className="invalid-feedback">{errors.email[0]}</div> : null }
                        </div>
                        <div className="mb-4">
                            <label htmlFor="password" className="form-label">Password</label>
                            <input type="password" id="password" className={classNames('form-control', { 'is-invalid': errors.password })} {...register('password')} />
                            { errors.password ? <div className="invalid-feedback">{errors.password[0]}</div> : null }
                        </div>
                        <div className="mb-4">
                            <label htmlFor="password_confirmation" className="form-label">Password Confirmation</label>
                            <input type="password" id="password_confirmation" className={classNames('form-control', { 'is-invalid': errors.password_confirmation })} {...register('password_confirmation')} />
                            { errors.password_confirmation ? <div className="invalid-feedback">{errors.password_confirmation[0]}</div> : null }
                        </div>
                        <div className="mb-4">
                            <label htmlFor="role" className="form-label">Role</label>
                            <select id="role" className={classNames('form-select', { 'is-invalid': errors.role })} {...register('role')}>
                                <option value="admin">Admin</option>
                                <option value="client">Client</option>
                            </select>
                            { errors.role ? <div className="invalid-feedback">{errors.role[0]}</div> : null }
                        </div>
                        <div className="mb-4 form-check">
                            <input type="checkbox" id="enabled" className={classNames('form-check-input', { 'is-invalid': errors.enabled })} {...register('enabled')} />
                            <label htmlFor="enabled" className="form-check-label">Enabled</label>
                            { errors.enabled ? <div className="invalid-feedback">{errors.enabled[0]}</div> : null }
                        </div>
                        <div className="d-flex justify-content-end">
                            <Link to="/users" className="btn btn-link">Back to users</Link>
                            <button type="submit" className="btn btn-primary px-4">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    );
}

// resources/js/admin/users/UserCreate.vue
<template>
    <div class="container">
        <div class="card border-0 shadow mt-4 mw-50e mx-auto">
            <div class="card-body">
                <form action="#" @submit.prevent="onSubmit">
                    <div class="mb-4">
                        <label for="name" class="form-label">Name</label>
                        <input type="text" id="name" class="form-control" :class="{'is-invalid': errors.name}" v-model="form.name" />
                        <div v-if="errors.name" class="invalid-feedback">{{ errors.name[0] }}</div>
                    </div>
                    <div class="mb-4">
                        <label for="email" class="form-label">Email</label>
                        <input type="email" id="email" class="form-control" :class="{'is-invalid': errors.email}" v-model="form.email" />
                        <div v-if="errors.email" class="invalid-feedback">{{ errors.email[0] }}</div>
                    </div>
                    <div class="mb-4">
                        <label for="password" class="form-label">Password</label>
                        <input type="password" id="password" class="form-control" :class="{'is-invalid': errors.password}" v-model="form.password" />
                        <div v-if="errors.password" class="invalid-feedback">{{ errors.password[0] }}</div>
                    </div>
                    <div class="mb-4">
                        <label for="password_confirmation" class="form-label">Password Confirmation</label>
                        <input type="password" id="password_confirmation" class="form-control" :class="{'is-invalid': errors.password_confirmation}" v-model="form.password_confirmation" />
                        <div v-if="errors.password_confirmation" class="invalid-feedback">{{ errors.password_confirmation[0] }}</div>
                    </div>
                    <div class="mb-4">
                        <label for="role" class="form-label">Role</label>
                        <select id="role" class="form-select" :class="{'is-invalid': errors.role}" v-model="form.role">
                        <option value="admin">Admin</option>
                        <option value="client">Client</option>
                        </select>
                        <div v-if="errors.role" class="invalid-feedback">{{ errors.role[0] }}</div>
                    </div>
                    <div class="mb-4 form-check">
                        <input type="checkbox" id="enabled" class="form-check-input" :class="{'is-invalid': errors.enabled}" v-model="form.enabled" />
                        <label for="enabled" class="form-check-label">Enabled</label>
                        <div v-if="errors.enabled" class="invalid-feedback">{{ errors.enabled[0] }}</div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <router-link to="/users" class="btn btn-link">Back to users</router-link>
                        <button type="submit" class="btn btn-primary px-4">Save</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</template>

<script setup>
import { reactive, ref } from 'vue';
import axios from 'axios';
import { useRouter } from 'vue-router';

const router = useRouter();

const errors = ref({});
const form = reactive({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
    role: 'client',
    enabled: true,
});

function onSubmit() {
    axios.post('/users', form)
        .then(() => {
            window.dispatchEvent(new CustomEvent('submit-notification', {
                detail: { type: 'success', message: 'User created.' }
            }));
            router.push('/users');
        })
        .catch(err => {
            if (err.response.status === 422) {
                errors.value = err.response.data.errors;
            }
        });
}
</script>
