// resources/js/admin/users/UserUpdate.jsx
import React from 'react';
import { useParams } from 'react-router-dom';
import UserUpdateForm from './components/UserUpdateForm';
import UserUpdatePasswordForm from './components/UserUpdatePasswordForm';
import useDataLoader from '../core/hooks/useDataLoader';

export default function UserUpdate() {
    const params = useParams();
    const [user, loading, errors] = useDataLoader(`/users/${params.id}`, null);

    if (loading) return (
        <div className="center-position">
            <div className="spinner-border text-primary spinner-lg" role="status">
                <span className="visually-hidden">Loading...</span>
            </div>
        </div>
    );

    if (errors) return <h3 className="text-center mt-4">Cannot load the data</h3>;

    return (
        <div className="container">
            <div className="card border-0 shadow mt-4 mw-50e mx-auto">
                <div className="card-body">
                    <UserUpdateForm user={user} />
                </div>
            </div>
            <div className="card border-0 shadow mt-4 mw-50e mx-auto">
                <div className="card-body">
                    <UserUpdatePasswordForm user={user} />
                </div>
            </div>
        </div>
    );
}

// resources/js/admin/users/UserUpdate.vue
<template>
    <Spinner v-if="loading"/>

    <h3 v-if="errors" class="text-center mt-4">Cannot load the data</h3>

    <div v-if="!loading" class="container">
        <div class="card border-0 shadow mt-4 mw-50e mx-auto">
            <div class="card-body">
                <UserUpdateForm :user="data" />
            </div>
        </div>
        <div class="card border-0 shadow mt-4 mw-50e mx-auto">
            <div class="card-body">
                <UserUpdatePasswordForm :user="data" />
            </div>
        </div>
    </div>
</template>

<script setup>
import { onMounted, ref } from 'vue';
import axios from 'axios';
import UserUpdatePasswordForm from './components/UserUpdatePasswordForm.vue';
import UserUpdateForm from './components/UserUpdateForm.vue';
import { useRoute } from 'vue-router';
import Spinner from '../core/components/Spinner.vue';

const route = useRoute();

const loading = ref(true);
const errors = ref(false);
const data = ref([]);

onMounted(() => {
    axios.get(`/users/${route.params.id}`)
        .then(response => data.value = response.data)
        .catch(() => errors.value = true)
        .finally(() => loading.value = false);
})
</script>
